### PR TITLE
unnecessary code removed

### PR DESCRIPTION
**Pull request by henrykumbrasevic**

### CODE REVIEW

**Review by mutemutemute — APPROVED** [review]
AMAZING !!! NO BUGS IN CONSOLE !!

**Review by caelihyacinthus — APPROVED** [review]
console.log in our code? more likely than you think

**Comment by henrykumbrasevic** [comment]
> AMAZING !!! NO BUGS IN CONSOLE !!

Yes. Is very good thanks you for you good koment

**Comment by Marerro** [comment]
I'm very impressed about this update!! Good job!!

**Pull request merged**
